### PR TITLE
Cogawrettes patch 1

### PR DESCRIPTION
**Pull request by cogawrettes**

### CODE REVIEW

**Comment by cogawrettes** [comment]
Hope I did this right! @chase-manning

**Review by cogawrettes — COMMENTED** [review]
adding lawbsters

**Comment by chase-manning** [comment]
Yes looks great!! Thanks so much @cogawrettes <3

Milady

**Comment by cogawrettes** [comment]
Sure thing, @chase-manning! Next, I think we need a family tree view of these derivatives. I am not aware of anyone else who has tried to do that. 

Milady

**Pull request merged**
