### PR TITLE
add vip please

### PR DESCRIPTION
**Pull request by riotgoools**
<3

### CODE REVIEW

**Comment by chase-manning** [comment]
@riotgoools Thanks so much for raising the PR! Would you be able to please make a couple of small changes/fixes? 

Currently the name of the image file is `vipimg.png`, but in the data the name is set to `vip.png`, which will result in the image not showing. Can you please change the image name or the data so that they match?

Also, for all other collections, we don't show a 'logo' for the project, but we always show a real example NFT from the collection. This is to make it easier for users browsing the site to see what the actual NFTs in the collection look like. Instead of just seeing a bunch of logos and then having to click on each collection to see the NFTs. Could you please update the image to be the image of one of the NFTs in the collection?

Thanks so much! 🙏🏻

**Comment by riotgoools** [comment]
Hi @chase-manning!

Oops 😓 sorry, I forgot that part of the file name. And that isn't a logo, it's what the nfts actually look like but because they have transparent backgrounds, I put it on a "transparent" grid for this. I'll update with a fully transparent one. Thanks!

**Comment by chase-manning** [comment]
Yay! Looks great!! Thanks so much @riotgoools <3

Milady

**Comment by riotgoools** [comment]
🖤🖤🖤 thanks @chase-manning!

milady

**Pull request merged**
